/*
    rstanemax is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rstanemax is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rstanemax.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0

#include <stan/model/model_header.hpp>

namespace model_MLmodel_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_MLmodel");
    reader.add_event(64, 62, "end", "model_MLmodel");
    return reader;
}

class model_MLmodel
  : public stan::model::model_base_crtp<model_MLmodel> {
private:
        int N;
        int P;
        std::vector<int> y;
        matrix_d X;
        double sigma_prior;
        int make_pred;
        int N_pred;
        matrix_d X_pred;
public:
    model_MLmodel(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_MLmodel(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_MLmodel_namespace::model_MLmodel";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            // initialize data block variables from context__
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);

            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "P", "int", context__.to_vec());
            P = int(0);
            vals_i__ = context__.vals_i("P");
            pos__ = 0;
            P = vals_i__[pos__++];
            check_greater_or_equal(function__, "P", P, 1);

            current_statement_begin__ = 8;
            validate_non_negative_index("y", "N", N);
            context__.validate_dims("data initialization", "y", "int", context__.to_vec(N));
            y = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("y");
            pos__ = 0;
            size_t y_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                y[k_0__] = vals_i__[pos__++];
            }

            current_statement_begin__ = 9;
            validate_non_negative_index("X", "N", N);
            validate_non_negative_index("X", "P", P);
            context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(N,P));
            X = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, P);
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_j_2_max__ = P;
            size_t X_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < X_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_j_1_max__; ++j_1__) {
                    X(j_1__, j_2__) = vals_r__[pos__++];
                }
            }

            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "sigma_prior", "double", context__.to_vec());
            sigma_prior = double(0);
            vals_r__ = context__.vals_r("sigma_prior");
            pos__ = 0;
            sigma_prior = vals_r__[pos__++];

            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "make_pred", "int", context__.to_vec());
            make_pred = int(0);
            vals_i__ = context__.vals_i("make_pred");
            pos__ = 0;
            make_pred = vals_i__[pos__++];
            check_greater_or_equal(function__, "make_pred", make_pred, 0);
            check_less_or_equal(function__, "make_pred", make_pred, 1);

            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "N_pred", "int", context__.to_vec());
            N_pred = int(0);
            vals_i__ = context__.vals_i("N_pred");
            pos__ = 0;
            N_pred = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_pred", N_pred, 1);

            current_statement_begin__ = 14;
            validate_non_negative_index("X_pred", "N_pred", N_pred);
            validate_non_negative_index("X_pred", "P", P);
            context__.validate_dims("data initialization", "X_pred", "matrix_d", context__.to_vec(N_pred,P));
            X_pred = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N_pred, P);
            vals_r__ = context__.vals_r("X_pred");
            pos__ = 0;
            size_t X_pred_j_2_max__ = P;
            size_t X_pred_j_1_max__ = N_pred;
            for (size_t j_2__ = 0; j_2__ < X_pred_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_pred_j_1_max__; ++j_1__) {
                    X_pred(j_1__, j_2__) = vals_r__[pos__++];
                }
            }


            // initialize transformed data variables
            // execute transformed data statements

            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 18;
            validate_non_negative_index("cutpoints", "2", 2);
            num_params_r__ += 2;
            current_statement_begin__ = 19;
            validate_non_negative_index("beta", "P", P);
            num_params_r__ += P;
            current_statement_begin__ = 20;
            num_params_r__ += 1;
            current_statement_begin__ = 21;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_MLmodel() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        current_statement_begin__ = 18;
        if (!(context__.contains_r("cutpoints")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable cutpoints missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("cutpoints");
        pos__ = 0U;
        validate_non_negative_index("cutpoints", "2", 2);
        context__.validate_dims("parameter initialization", "cutpoints", "vector_d", context__.to_vec(2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> cutpoints(2);
        size_t cutpoints_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < cutpoints_j_1_max__; ++j_1__) {
            cutpoints(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.ordered_unconstrain(cutpoints);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable cutpoints: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 19;
        if (!(context__.contains_r("beta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta");
        pos__ = 0U;
        validate_non_negative_index("beta", "P", P);
        context__.validate_dims("parameter initialization", "beta", "vector_d", context__.to_vec(P));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta(P);
        size_t beta_j_1_max__ = P;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            beta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 20;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 21;
        if (!(context__.contains_r("mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu", "double", context__.to_vec());
        double mu(0);
        mu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);

            // model parameters
            current_statement_begin__ = 18;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> cutpoints;
            (void) cutpoints;  // dummy to suppress unused var warning
            if (jacobian__)
                cutpoints = in__.ordered_constrain(2, lp__);
            else
                cutpoints = in__.ordered_constrain(2);

            current_statement_begin__ = 19;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta;
            (void) beta;  // dummy to suppress unused var warning
            if (jacobian__)
                beta = in__.vector_constrain(P, lp__);
            else
                beta = in__.vector_constrain(P);

            current_statement_begin__ = 20;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);

            current_statement_begin__ = 21;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            if (jacobian__)
                mu = in__.scalar_constrain(lp__);
            else
                mu = in__.scalar_constrain();

            // model body
            {
            current_statement_begin__ = 25;
            validate_non_negative_index("eta", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> eta(N);
            stan::math::initialize(eta, DUMMY_VAR__);
            stan::math::fill(eta, DUMMY_VAR__);


            current_statement_begin__ = 27;
            lp_accum__.add(normal_log<propto__>(cutpoints, 0, 20));
            current_statement_begin__ = 30;
            lp_accum__.add(normal_log<propto__>(sigma, 0, sigma_prior));
            current_statement_begin__ = 31;
            lp_accum__.add(normal_log<propto__>(mu, 0, 2));
            current_statement_begin__ = 32;
            lp_accum__.add(double_exponential_log<propto__>(beta, mu, sigma));
            current_statement_begin__ = 35;
            stan::math::assign(eta, multiply(X, beta));
            current_statement_begin__ = 36;
            for (int i = 1; i <= N; ++i) {

                current_statement_begin__ = 37;
                lp_accum__.add(ordered_logistic_log<propto__>(get_base1(y, i, "y", 1), get_base1(eta, i, "eta", 1), cutpoints));
            }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("cutpoints");
        names__.push_back("beta");
        names__.push_back("sigma");
        names__.push_back("mu");
        names__.push_back("eta");
        names__.push_back("log_lik");
        names__.push_back("train_pred");
        names__.push_back("ypred");
        names__.push_back("eta_pred");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(P);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(make_pred, 1) ? N_pred : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(make_pred, 1) ? N_pred : 0 ));
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_MLmodel_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning

        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> cutpoints = in__.ordered_constrain(2);
        size_t cutpoints_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < cutpoints_j_1_max__; ++j_1__) {
            vars__.push_back(cutpoints(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> beta = in__.vector_constrain(P);
        size_t beta_j_1_max__ = P;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            vars__.push_back(beta(j_1__));
        }

        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);

        double mu = in__.scalar_constrain();
        vars__.push_back(mu);

        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        if (!include_tparams__ && !include_gqs__) return;

        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 42;
            validate_non_negative_index("eta", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> eta(N);
            stan::math::initialize(eta, DUMMY_VAR__);
            stan::math::fill(eta, DUMMY_VAR__);

            current_statement_begin__ = 43;
            validate_non_negative_index("log_lik", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(N);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);

            current_statement_begin__ = 44;
            validate_non_negative_index("train_pred", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> train_pred(N);
            stan::math::initialize(train_pred, DUMMY_VAR__);
            stan::math::fill(train_pred, DUMMY_VAR__);

            current_statement_begin__ = 45;
            validate_non_negative_index("ypred", "(logical_eq(make_pred, 1) ? N_pred : 0 )", (logical_eq(make_pred, 1) ? N_pred : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> ypred((logical_eq(make_pred, 1) ? N_pred : 0 ));
            stan::math::initialize(ypred, DUMMY_VAR__);
            stan::math::fill(ypred, DUMMY_VAR__);

            current_statement_begin__ = 46;
            validate_non_negative_index("eta_pred", "(logical_eq(make_pred, 1) ? N_pred : 0 )", (logical_eq(make_pred, 1) ? N_pred : 0 ));
            Eigen::Matrix<double, Eigen::Dynamic, 1> eta_pred((logical_eq(make_pred, 1) ? N_pred : 0 ));
            stan::math::initialize(eta_pred, DUMMY_VAR__);
            stan::math::fill(eta_pred, DUMMY_VAR__);

            // generated quantities statements
            current_statement_begin__ = 48;
            stan::math::assign(eta, multiply(X, beta));
            current_statement_begin__ = 49;
            for (int i = 1; i <= N; ++i) {

                current_statement_begin__ = 50;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ordered_logistic_log(get_base1(y, i, "y", 1), get_base1(eta, i, "eta", 1), cutpoints), 
                            "assigning variable log_lik");
                current_statement_begin__ = 51;
                stan::model::assign(train_pred, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ordered_logistic_rng(get_base1(eta, i, "eta", 1), cutpoints, base_rng__), 
                            "assigning variable train_pred");
            }
            current_statement_begin__ = 55;
            if (as_bool(logical_eq(make_pred, 1))) {

                current_statement_begin__ = 56;
                stan::math::assign(eta_pred, multiply(X_pred, beta));
                current_statement_begin__ = 57;
                for (int j = 1; j <= N_pred; ++j) {

                    current_statement_begin__ = 58;
                    stan::model::assign(ypred, 
                                stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                                ordered_logistic_rng(get_base1(eta_pred, j, "eta_pred", 1), cutpoints, base_rng__), 
                                "assigning variable ypred");
                }
            }

            // validate, write generated quantities
            current_statement_begin__ = 42;
            size_t eta_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
                vars__.push_back(eta(j_1__));
            }

            current_statement_begin__ = 43;
            size_t log_lik_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }

            current_statement_begin__ = 44;
            size_t train_pred_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < train_pred_j_1_max__; ++j_1__) {
                vars__.push_back(train_pred(j_1__));
            }

            current_statement_begin__ = 45;
            size_t ypred_j_1_max__ = (logical_eq(make_pred, 1) ? N_pred : 0 );
            for (size_t j_1__ = 0; j_1__ < ypred_j_1_max__; ++j_1__) {
                vars__.push_back(ypred(j_1__));
            }

            current_statement_begin__ = 46;
            size_t eta_pred_j_1_max__ = (logical_eq(make_pred, 1) ? N_pred : 0 );
            for (size_t j_1__ = 0; j_1__ < eta_pred_j_1_max__; ++j_1__) {
                vars__.push_back(eta_pred(j_1__));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    std::string model_name() const {
        return "model_MLmodel";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t cutpoints_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < cutpoints_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "cutpoints" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_j_1_max__ = P;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }

        if (!include_gqs__) return;
        size_t eta_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t train_pred_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < train_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "train_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t ypred_j_1_max__ = (logical_eq(make_pred, 1) ? N_pred : 0 );
        for (size_t j_1__ = 0; j_1__ < ypred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ypred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t eta_pred_j_1_max__ = (logical_eq(make_pred, 1) ? N_pred : 0 );
        for (size_t j_1__ = 0; j_1__ < eta_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t cutpoints_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < cutpoints_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "cutpoints" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_j_1_max__ = P;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }

        if (!include_gqs__) return;
        size_t eta_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t train_pred_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < train_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "train_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t ypred_j_1_max__ = (logical_eq(make_pred, 1) ? N_pred : 0 );
        for (size_t j_1__ = 0; j_1__ < ypred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ypred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t eta_pred_j_1_max__ = (logical_eq(make_pred, 1) ? N_pred : 0 );
        for (size_t j_1__ = 0; j_1__ < eta_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }

}; // model

}  // namespace

typedef model_MLmodel_namespace::model_MLmodel stan_model;

#ifndef USING_R

stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


#endif
